---
name: CI

on: push

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint ${{ matrix.check }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        check: [isort, mypy, black, flake8]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Setup Python ${{ steps.versions.outputs.python }}
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ steps.versions.outputs.python }}
          poetry-version: ${{ steps.versions.outputs.poetry }}

      - name: Run linter
        run: make lint-${{ matrix.check }}

  test:
    name: Test pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Setup Python ${{ steps.versions.outputs.python }}
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ steps.versions.outputs.python }}
          poetry-version: ${{ steps.versions.outputs.poetry }}

      - name: Run pytest
        run: make test
        env:
          TEST_COV_REP: term
