---
name: CI

on: push

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint ${{ matrix.check }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        check: [mypy, ruff-check, ruff-format]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up mise (python, uv)
        uses: jdx/mise-action@v4

      - name: Run linter
        run: mise run lint:${{ matrix.check }}

  test:
    name: Test pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up mise (python, uv)
        uses: jdx/mise-action@v4

      - name: Run pytest
        run: mise run test
        env:
          TEST_COV_REP: term
