name: "[lint] Commit is conventional"

on:
  pull_request_target:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - synchronize

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  lint:
    name: Lint
    uses: kolonialno/actions/.github/workflows/pr-conventional-commit.yml@main
