---
name: "[release] Upload artifacts"

on:
  # Manually triggering this from main branch
  # will upload artifacts to current release.
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag to checkout. View tags at https://github.com/kolonialno/troncos/tags
        default: ""
  push:
    branches:
      - release-test-**
  release:
    types:
      # Trigger on creation of a draft is not possible
      # https://github.com/orgs/community/discussions/7118
      # ref https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      # This will trigger when a pre-release is created, but not when published.
      - prereleased

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Tag on commit
    outputs:
      upload: ${{ steps.tag.outputs.upload }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ github.event.inputs.tag == '' }}

      - name: Checkout tag (workflow_dispatch)
        uses: actions/checkout@v4
        if: ${{ github.event.inputs.tag != '' }}
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
    
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ steps.versions.outputs.python }}
          poetry-version: ${{ steps.versions.outputs.poetry }}

        # Only upload if current commit has a tag that match the version in
        # Pyproject. This will only be the case for a troncos tag that has format
        # x.y.z
        # The other releases have component name prefixed. Eaxmple: component-x.y.z.
      - name: Verify semVer tag on commit
        id: tag
        run: |
          set -ex
          if [ "${{ github.event.inputs.tag }}" == '' ]; then

            tag=$(git tag --points-at ${{ github.sha }})
            echo tag=$tag
            echo "tag=$tag" >> $GITHUB_OUTPUT;

            project_version=$(poetry version -s)
            echo project_version=$project_version

            if [ "$tag" == "$project_version" ]; then
              echo "upload=true" >> $GITHUB_OUTPUT;
            else
              echo "upload=false" >> $GITHUB_OUTPUT;
            fi
          else
            echo "upload=true" >> $GITHUB_OUTPUT;
          fi

  python_package:
    runs-on: ubuntu-latest
    name: Python package
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ github.event.inputs.tag == '' }}

      - name: Checkout tag (workflow_dispatch)
        uses: actions/checkout@v4
        if: ${{ github.event.inputs.tag != '' }}
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
  
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ steps.versions.outputs.python }}
          poetry-version: ${{ steps.versions.outputs.poetry }}

      - name: Publish Troncos Python  package
        if: ${{ needs.tag.outputs.upload == 'true' }}
        run: |
          set -ex
          make release

  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs:
      - python_package
      - tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish pre-release
        if: ${{ needs.tag.outputs.upload == 'true' }}
        run: |
          set -ex
          gh release edit ${{ needs.tag.outputs.tag }} --prerelease=false --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
