name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    name: Release to PYPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up mise (python, uv)
      uses: jdx/mise-action@v4

    - run: mise run release
