name: Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.2.1"
  POETRY_HOME: "/home/runner/.poetry"
  PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    name: Release to PYPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup project
      uses: ./.github/actions/setup-project
    - run: make release