name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"

jobs:
  release:
    name: Release to PYPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Read .tool-versions
      uses: marocchino/tool-versions-action@v1
      id: versions

    - name: Setup Python ${{ steps.versions.outputs.python }}
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ steps.versions.outputs.python }}
        poetry-version: ${{ steps.versions.outputs.poetry }}

    - run: make release
